# ~/.config/starship.toml

[python]
symbol = "ğŸ "
python_binary = "python3"

[rust]
symbol = "ğŸ¦€ "

[jobs]
symbol = " ğŸŸ…"
style = "bold blue"

# [status]
# format = '[\[$symbol $common_meaning$signal_name$maybe_int\]]($style) '
# map_symbol = true
# disabled = false
