# ~/.config/starship.toml

# scan_timeout = 1
# command_timeout = 200

[python]
symbol = "ğŸ "
python_binary = "python3"

[c]
disabled = true

[nodejs]
disabled = true

[rust]
symbol = "ğŸ¦€ "

[jobs]
symbol = " !"
style = "bold blue"

[hostname]
disabled = true
